
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author olibou
 */
public class vote extends javax.swing.JFrame {

    /**
     * Creates new form vote
     */
    public vote() {
        initComponents();
        jTextArea1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jButton4.setVisible(false);
    }

    private int nbQuestion = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sondage numero");
        jLabel1.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Repondre au sondage");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Question numero :");
        jLabel2.setToolTipText("");

        jLabel3.setText("choix :");
        jLabel3.setToolTipText("");

        jButton2.setText("ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ok");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Voir les resultats");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jButton2.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField2.setText("1");
        
        //Variable permettant de sauvegarder le fichier JSON envoye par le web service
        StringBuilder rep = new StringBuilder();
        
        try{ 
            //Configuration de l’URL
            URL url = new URL("http://localhost:8080/ServeurAppSondage/webresources/GestionSondage/nbQuestion/"+jTextField1.getText());
            //Configuration de la connexion
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();      
            conn.setRequestMethod("GET");       
            //Connexion au web service
            conn.connect();
            // Declaration du flux et du buffer de reception
            InputStream in = conn.getInputStream();
            BufferedReader BufferReception = new BufferedReader(new InputStreamReader(in));;
            String LigneReponse;
            try{
                do {
                    //Recuperer la reponse et stocker dans la variable rep (2 lignes)
                    LigneReponse = BufferReception.readLine();
                    if (LigneReponse!=null){
                        rep.append(LigneReponse+"\n");
                    }
                } while (LigneReponse!= null && LigneReponse.length() > 0);        
            }catch (Exception e){System.out.println(e.getMessage());}
            
            nbQuestion = Integer.valueOf(rep.toString().trim());
            
            //Fermeture de la connexion
            conn.disconnect();
            
        }catch (Exception e){System.out.println(e.getMessage());}
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        nbQuestion = nbQuestion - 1;
        if (nbQuestion == 0)
        {
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jButton2.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
        }
        int question = Integer.valueOf(jTextField2.getText());
        question = question + 1;
        jTextField2.setText((Integer.toString(question)));
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        jTextArea1.setVisible(true);
        jButton1.setVisible(true);
        jButton4.setVisible(true);
    
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Afficher le sondage
                  
        //Variable permettant de sauvegarder le fichier JSON envoye par le web service
        StringBuilder rep = new StringBuilder();
        
        try{ 
            //Configuration de l’URL
            URL url = new URL("http://localhost:8080/ServeurAppSondage/webresources/GestionSondage/AfficherSondage/"+jTextField1.getText());
            //Configuration de la connexion
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();      
            conn.setRequestMethod("GET");       
            //Connexion au web service
            conn.connect();
            // Declaration du flux et du buffer de reception
            InputStream in = conn.getInputStream();
            BufferedReader BufferReception = new BufferedReader(new InputStreamReader(in));;
            String LigneReponse;
            try{
                do {
                    //Recuperer la reponse et stocker dans la variable rep (2 lignes)
                    LigneReponse = BufferReception.readLine();
                    if (LigneReponse!=null){
                        rep.append(LigneReponse+"\n");
                    }
                } while (LigneReponse!= null && LigneReponse.length() > 0);        
            }catch (Exception e){System.out.println(e.getMessage());}
            
            //Fermeture de la connexion
            conn.disconnect();
            
        }catch (Exception e){System.out.println(e.getMessage());}
        jTextArea1.setText(rep.toString());
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Variable permettant de sauvegarder le fichier JSON envoye par le web service
        StringBuilder rep = new StringBuilder();
        
        try{ 
            //Configuration de l’URL
            URL url = new URL("http://localhost:8080/ServeurAppSondage/webresources/GestionSondage/AjouterVote/"+jTextField1.getText()+"/question/"+jTextField2.getText()+"/vote/"+jTextField3.getText());
            //Configuration de la connexion
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();      
            conn.setRequestMethod("POST");       
            //Connexion au web service
            conn.connect();
            // Declaration du flux et du buffer de reception
            InputStream in = conn.getInputStream();
            BufferedReader BufferReception = new BufferedReader(new InputStreamReader(in));;
            String LigneReponse = "";
            try{
                do {
                    //Recuperer la reponse et stocker dans la variable rep (2 lignes)
                    LigneReponse = BufferReception.readLine();
                    if (LigneReponse!=null){
                        rep.append(LigneReponse+"\n");
                    }
                } while (LigneReponse!= null && LigneReponse.length() > 0);        
            }catch (Exception e){System.out.println(e.getMessage());}
            
            //Fermeture de la connexion
            conn.disconnect();
            
            jTextField3.setText("");
            
        }catch (Exception e){System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Variable permettant de sauvegarder le fichier JSON envoye par le web service
        StringBuilder rep = new StringBuilder();
        
        try{ 
            //Configuration de l’URL
            URL url = new URL("http://localhost:8080/ServeurAppSondage/webresources/GestionSondage/AfficherResultatSondage/"+jTextField1.getText());
            //Configuration de la connexion
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();      
            conn.setRequestMethod("GET");       
            //Connexion au web service
            conn.connect();
            // Declaration du flux et du buffer de reception
            InputStream in = conn.getInputStream();
            BufferedReader BufferReception = new BufferedReader(new InputStreamReader(in));;
            String LigneReponse = "";
            try{
                do {
                    //Recuperer la reponse et stocker dans la variable rep (2 lignes)
                    LigneReponse = BufferReception.readLine();
                    if (LigneReponse!=null){
                        rep.append(LigneReponse+"\n");
                    }
                } while (LigneReponse!= null && LigneReponse.length() > 0);        
            }catch (Exception e){System.out.println(e.getMessage());}
            
            jTextArea1.setText(rep.toString());
            
            //Fermeture de la connexion
            conn.disconnect();
            
        }catch (Exception e){System.out.println(e.getMessage());}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vote().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
